Repository MusicDigging/Mudig_FE, pull requests merged in 2023-12, with the labels that each got.

#49 생성 요약 페이지 구현
  src/components/PlaylistDetail/DetailList.jsx
  src/components/PlaylistDetail/PlayListInfo.jsx
  src/components/PlaylistSummary/PlaylistPrivateCheck.jsx
  src/components/common/Modal/Modal.jsx
  src/img/extend-icon.svg
  src/pages/PlaylistSummary/PlaylistSummary.jsx
  src/routes/Router.jsx
Labels: 🎨 Style, [FE] 이지수

#42 style: Follow Page UI 구현
  src/App.js
  src/components/Profile/FollowUserList.jsx
  src/components/common/NavBar/NavBar.jsx
  src/components/common/User.jsx
  src/img/icon_home.svg
  src/img/icon_movie.svg
  src/img/icon_my_page.svg
  src/img/icon_playlist.svg
  src/img/icon_search.svg
  src/pages/Profile/Follow.jsx
Labels: 🎨 Style, [FE] 김예지

#52 플리 수정 모달 구현
  src/App.js
  src/atoms/modalAtom.js
  src/components/PlaylistDetail/DetailList.jsx
  src/components/PlaylistDetail/MusicPlayBar.jsx
  src/components/PlaylistDetail/PlayListInfo.jsx
  src/components/PlaylistSummary/PlaylistPrivateCheck.jsx
  src/components/common/Modal/Modal.jsx
  src/img/arrow-icon.svg
  src/pages/PlaylistModify/PlaylistModify.jsx
  src/pages/PlaylistSummary/PlaylistSummary.jsx
  src/pages/Search/SearchResult.jsx
  src/routes/Router.jsx
Labels: 🎨 Style, [FE] 이지수

#58 검색 페이지 결과 컴포넌트 분리
  src/components/Search/SearchInput.jsx
  src/components/Search/SearchResultByType.jsx
  src/pages/Search/SearchResult.jsx
  src/pages/Search/SearchResultStyle.jsx
  src/routes/Router.jsx
Labels: 🎨 Style, [FE] 이지수

#66 검색 기능 구현
  src/components/Search/EmptySearch.jsx
  src/components/Search/RecentSearch.jsx
  src/components/Search/SearchInput.jsx
  src/components/Search/SearchNav.jsx
  src/components/Search/SearchResultAll.jsx
  src/components/Search/SearchResultByType.jsx
  src/components/common/PlayList/PlayListItem.jsx
  src/pages/Search/Search.jsx
  src/pages/Search/SearchResult.jsx
  src/pages/Search/SearchStyle.jsx
  src/routes/Router.jsx
Labels: ✨ Feat, [FE] 이지수

#67 프로필 페이지 기능 구현, 프로필 수정 페이지 UI 수정
  src/components/Profile/MainPlayList.jsx
  src/components/Profile/MainPlayListSection.jsx
  src/components/Profile/PlayListSection.jsx
  src/components/Profile/ProfileSection.jsx
  src/components/common/Image/Image.jsx
  src/components/common/Image/ProfileImage.jsx
  src/components/common/Input/ProfileInput.jsx
  src/components/common/PlayList/PlayListItem.jsx
  src/hooks/queries/usePlaylist.jsx
  src/hooks/queries/useProfile.jsx
  src/pages/EditProfile/EditProfile.jsx
  src/pages/EditProfile/EditProfileStyle.jsx
  src/pages/Profile/MyProfile.jsx
  src/pages/Profile/OtherProfile.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileStyle.jsx
  src/pages/SetProfile/SetProfile.jsx
  src/routes/Router.jsx
Labels: ✨ Feat, 🖊️ Rename, [FE] 차다연

#71 플리 생성 페이지 기능 구현
  src/components/Loading/Loading.jsx
  src/components/NewPlaylist/NewPlaylistChip.jsx
  src/hooks/queries/usePlaylist.jsx
  src/img/character-img.svg
  src/pages/CreatePlaylist/CreatePlaylist1.jsx
  src/pages/CreatePlaylist/CreatePlaylist2.jsx
  src/pages/CreatePlaylist/CreatePlaylist3.jsx
  src/pages/CreatePlaylist/CreatePlaylistStyle.jsx
  src/pages/NewPlaylist/Create/CreateNewPlaylist1.jsx
  src/pages/NewPlaylist/Create/CreateNewPlaylist2.jsx
  src/pages/NewPlaylist/Create/CreateNewPlaylist3.jsx
  src/pages/NewPlaylist/NewPlaylist.jsx
  src/pages/NewPlaylist/NewPlaylistStyle.jsx
  src/routes/Router.jsx
Labels: ✨ Feat, 🖊️ Rename, 🎨 Style, [FE] 차다연

#74 플리상세 페이지 - 음악영상 재생 기능 구현
  src/components/PlaylistDetail/CommentForm.jsx
  src/components/PlaylistDetail/DetailList.jsx
  src/components/PlaylistDetail/MusicPlayBar.jsx
  src/components/PlaylistDetail/MusicPlayer.jsx
  src/components/PlaylistDetail/PlayListInfo.jsx
  src/components/common/Layout/Layout.jsx
  src/components/common/Modal/MiniModal.jsx
  src/components/common/PlayList/PlayList.jsx
  src/pages/PlaylistDetail/PlaylistDetail.jsx
  src/routes/Router.jsx
Labels: ✨ Feat, [FE] 차다연

#72 뮤딕 로그인/ 소셜 로그인&회원가입 기능구현
  .env
  package-lock.json
  package.json
  src/components/common/Form/AuthForm.jsx
  src/library/apis/api.js
  src/library/atom.js
  src/pages/Login/Login.jsx
  src/pages/SetProfile/SetProfile.jsx
  src/pages/Signup/Signup.jsx
  src/pages/Signup/SignupDetail.jsx
Labels: ✨ Feat, [FE] 윤서준

#75 이벤트 페이지 기능구현
  package-lock.json
  src/img/eventPageBg.svg
  src/pages/EventPage/EventPage.jsx
  src/pages/EventPage/EventPageStyle.jsx
  src/routes/Router.jsx
Labels: ✨ Feat, [FE] 김예지

#77 프로필 설정에서 닉네임 중복검사 post 요청시 debounce 설정하기
  src/components/common/Input/ProfileInput.jsx
Labels: ✨ Feat, [FE] 윤서준

#79 플리 상세 페이지 - 댓글 기능 구현
  src/components/PlaylistDetail/CommentForm.jsx
  src/components/PlaylistDetail/CommentItem.jsx
  src/components/PlaylistDetail/CommentSection.jsx
  src/components/PlaylistDetail/DetailList.jsx
  src/components/PlaylistDetail/MusicPlayBar.jsx
  src/components/PlaylistDetail/PlayListInfo.jsx
  src/components/common/Layout/Layout.jsx
  src/components/common/Modal/MiniModal.jsx
  src/components/common/PlayList/PlayListItem.jsx
  src/hooks/queries/useComment.jsx
  src/pages/PlaylistDetail/PlaylistDetail.jsx
Labels: ✨ Feat, [FE] 차다연

#84 비밀번호 변경 페이지 기능구현 & 유저 정보 토큰 설정방식 변경
  package-lock.json
  package.json
  public/index.html
  src/components/common/Form/AuthForm.jsx
  src/components/common/Form/SignupForm.jsx
  src/components/common/Input/SignupInput.jsx
  src/hooks/queries/useUserInfo.jsx
  src/hooks/ussPasswordToggle.jsx
  src/library/atom.js
  src/pages/EventPage/EventPageStyle.jsx
  src/pages/Login/Login.jsx
  src/pages/SetProfile/SetProfile.jsx
  src/pages/UserInfo/ChangePwForm.jsx
  src/pages/UserInfo/UserLeaveForm.jsx
  src/routes/PrivateRoutes.js
Labels: ✨ Feat, [FE] 윤서준

#81 Home Page 기능구현
  src/components/Home/MyPlayListTable.jsx
  src/components/Home/PlayListTable.jsx
  src/components/common/Header/MainHeader.jsx
  src/components/common/Layout/Layout.jsx
  src/components/common/NavBar/NavBar.jsx
  src/hooks/queries/useHome.jsx
  src/img/home_icon.svg
  src/img/icon_home.svg
  src/img/icon_movie.svg
  src/img/icon_my_page.svg
  src/img/icon_playlist.svg
  src/img/movie_icon.svg
  src/img/playlist_icon.svg
  src/img/profile_icon.svg
  src/library/apis/axiosInstance.js
  src/pages/CreatePlaylist/CreatePlaylistStyle.jsx
  src/pages/EventPage/EventPageStyle.jsx
  src/pages/Home/Home.jsx
  src/pages/Home/HomeStyle.jsx
  src/pages/NotFound/NotFound.jsx
  src/routes/Router.jsx
Labels: ✨ Feat, [FE] 김예지

#83 플리 상세 페이지 - 플리 삭제, 좋아요, 기타 기능구현
  src/components/PlaylistDetail/CommentItem.jsx
  src/components/PlaylistDetail/CommentSection.jsx
  src/components/PlaylistDetail/MusicPlayBar.jsx
  src/hooks/queries/usePlaylist.jsx
  src/img/like-active-icon.svg
  src/img/like-icon.svg
  src/pages/PlaylistDetail/PlaylistDetail.jsx
  src/routes/Router.jsx
Labels: ✨ Feat, [FE] 차다연

#87 유저정보부분 확인작업
  src/components/common/Form/AuthForm.jsx
  src/components/common/Form/SignupForm.jsx
  src/pages/Login/Login.jsx
  src/pages/SetProfile/SetProfile.jsx
  src/pages/Signup/Signup.jsx
  src/pages/Signup/SignupDetail.jsx
  src/pages/Signup/SignupStyle.jsx
Labels: ♻️ Refactor, [FE] 윤서준

#89 플리 생성 요약 페이지 구현
  src/components/PlaylistDetail/PlayListInfo.jsx
  src/components/common/Image/Image.jsx
  src/pages/CreatePlaylist/CreatePlaylist3.jsx
  src/pages/EventPage/EventPage.jsx
  src/pages/PlaylistSummary/PlaylistSummary.jsx
Labels: ✨ Feat, [FE] 이지수

#92 플리 수정 페이지 기능 구현
  package-lock.json
  package.json
  src/components/PlaylistDetail/DetailList.jsx
  src/components/PlaylistDetail/MusicPlayBar.jsx
  src/components/PlaylistDetail/PlayListInfo.jsx
  src/components/PlaylistDetail/PlayListModify.jsx
  src/components/Profile/PlayListSection.jsx
  src/components/common/Modal/Modal.jsx
  src/components/common/PlayList/PlayList.jsx
  src/components/common/PlayList/PlayListItem.jsx
  src/hooks/queries/usePlaylist.jsx
  src/library/atom.js
  src/pages/PlaylistDetail/PlaylistDetail.jsx
  src/pages/PlaylistModify/PlaylistModify.jsx
Labels: ✨ Feat, [FE] 이지수

#91 프로필 페이지 기능 구현
  src/components/Profile/PlayListSection.jsx
  src/components/Profile/ProfileSection.jsx
  src/hooks/queries/useProfile.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileStyle.jsx
Labels: ✨ Feat, [FE] 차다연

#90 프로필 수정 페이지 기능 구현
  src/components/EditProfile/SetProfileImage.jsx
  src/components/EditProfile/SetRepPlaylist.jsx
  src/components/common/Button/Button.jsx
  src/components/common/Image/ProfileImage.jsx
  src/components/common/Input/ProfileInput.jsx
  src/hooks/queries/useProfile.jsx
  src/pages/EditProfile/EditProfile.jsx
  src/pages/EditProfile/EditProfileStyle.jsx
Labels: ✨ Feat, [FE] 차다연

#93 플리 생성 페이지 확인작업
  src/components/Loading/Loading.jsx
  src/pages/CreatePlaylist/CreatePlaylist1.jsx
  src/pages/CreatePlaylist/CreatePlaylist2.jsx
  src/pages/CreatePlaylist/CreatePlaylist3.jsx
  src/pages/CreatePlaylist/CreatePlaylistStyle.jsx
Labels: ✨ Feat, 🎨 Style, [FE] 차다연

#98 프로필 페이지 확인작업
  src/components/Profile/MainPlayList.jsx
  src/components/Profile/MainPlayListSection.jsx
  src/components/Profile/PlayListSection.jsx
  src/components/Profile/ProfileSection.jsx
Labels: ✨ Feat, 🎨 Style, [FE] 차다연

#97 플리 수정 삭제 버튼 위치 수정
  src/components/PlaylistDetail/PlayListModify.jsx
Labels: 🎨 Style, [FE] 이지수

#101 플리 생성 페이지 확인작업
  src/pages/CreatePlaylist/CreatePlaylist1.jsx
  src/pages/CreatePlaylist/CreatePlaylist2.jsx
  src/pages/CreatePlaylist/CreatePlaylist3.jsx
  src/pages/CreatePlaylist/CreatePlaylistStyle.jsx
Labels: 🐞 Fix, 🎨 Style, [FE] 차다연

#99 플리 상세 페이지 확인작업
  src/components/PlaylistDetail/CommentSection.jsx
  src/components/PlaylistDetail/DetailList.jsx
  src/components/PlaylistDetail/MusicPlayBar.jsx
  src/components/PlaylistDetail/PlayListInfo.jsx
  src/components/common/PlayList/PlayListItem.jsx
  src/img/share-icon.svg
  src/pages/PlaylistDetail/PlaylistDetail.jsx
Labels: ✨ Feat, 🎨 Style, [FE] 이지수, [FE] 차다연

#102 follow 페이지 기능구현
  src/components/Profile/FollowUserList.jsx
  src/components/Profile/ProfileSection.jsx
  src/components/common/User.jsx
  src/hooks/queries/useFollow.jsx
  src/pages/Profile/Follow.jsx
Labels: ✨ Feat, [FE] 김예지

#106 Style: 아이콘 크기 변경, 배경 색 변경
  src/components/Home/MyPlayListTable.jsx
  src/pages/PlaylistDetail/PlaylistDetail.jsx
Labels: 🐞 Fix, 🎨 Style, [FE] 김예지

#103 플리 수정 페이지 배경 이미지에 맞게 스타일 수정
  src/components/PlaylistDetail/PlayListModify.jsx
Labels: 🎨 Style, [FE] 이지수

#104 플리 요약 페이지 수정
  src/components/PlaylistDetail/PlayListInfo.jsx
  src/components/PlaylistSummary/PlaylistPrivateCheck.jsx
  src/pages/PlaylistSummary/PlaylistSummary.jsx
Labels: ✨ Feat, 🎨 Style, [FE] 이지수

#108 프로필 페이지 확인작업 2차
  src/pages/EditProfile/EditProfile.jsx
  src/pages/Profile/Profile.jsx
Labels: ✨ Feat, 🎨 Style, [FE] 차다연

#110 플리 상세 페이지 확인작업
  src/components/PlaylistDetail/CommentItem.jsx
  src/components/PlaylistDetail/MusicPlayer.jsx
  src/components/Profile/MainPlayListSection.jsx
  src/pages/Profile/Profile.jsx
Labels: ✨ Feat, [FE] 차다연

#107 홈 화면, 스플래쉬 화면 기능추가
  src/components/Home/MyPlayListTable.jsx
  src/pages/Home/Home.jsx
  src/pages/Splash/Splash.jsx
Labels: ✨ Feat, 🎨 Style, [FE] 김예지

#112 검색 페이지(리액트 쿼리 적용, 스타일 수정, etc)
  src/components/Search/RecentSearch.jsx
  src/components/Search/SearchResultAll.jsx
  src/components/Search/SearchResultByType.jsx
  src/hooks/queries/useSearch.jsx
  src/pages/Search/Search.jsx
  src/pages/Search/SearchResult.jsx
  src/pages/Search/SearchStyle.jsx
  src/routes/Router.jsx
Labels: ✨ Feat, ♻️ Refactor, 🎨 Style, [FE] 이지수

#114 팔로우 버그 수정
  src/components/Profile/FollowUserList.jsx
  src/components/common/User.jsx
  src/hooks/queries/useFollow.jsx
  src/hooks/queries/useProfile.jsx
  src/pages/Profile/Follow.jsx
Labels: 🐞 Fix, [FE] 김예지

#118 홈 페이지 마이플리 예외처리, 스플래쉬 페이지 인터렉션
  src/img/icon_splash_mudig.svg
  src/img/icon_splash_mudig_hand.svg
  src/pages/Home/Home.jsx
  src/pages/Home/HomeStyle.jsx
  src/pages/Splash/Splash.jsx
Labels: 🐞 Fix, 🎨 Style, [FE] 김예지

#117 로그인/ 회원가입 사용자 개선 사항
  src/components/common/Form/AuthForm.jsx
  src/components/common/Form/SignupForm.jsx
  src/library/atom.js
  src/pages/Login/Login.jsx
  src/pages/Signup/Signup.jsx
Labels: ♻️ Refactor, [FE] 윤서준

#121 플리 생성, 플리 상세 모바일 화면 잘림현상 수정
  src/pages/CreatePlaylist/CreatePlaylistStyle.jsx
Labels: 🐞 Fix, 🎨 Style, [FE] 차다연

#120 프로필 페이지 수정
  src/components/Profile/PlayListSection.jsx
  src/components/common/Image/Image.jsx
  src/components/common/Image/ProfileImage.jsx
  src/components/common/Input/ProfileInput.jsx
  src/hooks/queries/useProfile.jsx
  src/img/default-user-img.svg
  src/pages/EditProfile/EditProfile.jsx
  src/pages/EditProfile/EditProfileStyle.jsx
  src/pages/PlaylistDetail/PlaylistDetail.jsx
  src/pages/Profile/Profile.jsx
Labels: 🐞 Fix, ✨ Feat, 🎨 Style, [FE] 차다연

#128 플리 생성, 플리 상세 수정
  src/pages/CreatePlaylist/CreatePlaylist1.jsx
  src/pages/CreatePlaylist/CreatePlaylist3.jsx
  src/pages/CreatePlaylist/CreatePlaylistStyle.jsx
  src/pages/PlaylistDetail/PlaylistDetail.jsx
Labels: 🐞 Fix, 🎨 Style, [FE] 차다연

#124 로그인 페이지 디자인 확인
  src/components/common/Form/AuthForm.jsx
  src/components/common/Input/AuthInput.jsx
  src/pages/Login/Login.jsx
Labels: 🎨 Style, [FE] 윤서준

#126 랜덤뮤비 페이지 스타일 설정 수정
  src/components/common/Modal/AddModal.jsx
Labels: 🎨 Style, [FE] 윤서준

#135 검색 페이지 수정
  src/components/Search/SearchInput.jsx
  src/components/Search/SearchResultAll.jsx
  src/components/Search/SearchResultByType.jsx
  src/pages/Search/Search.jsx
  src/pages/Search/SearchResult.jsx
Labels: 🐞 Fix, ✨ Feat, 🎨 Style, [FE] 이지수

#129 프로필 페이지 확인작업 4차
  src/components/EditProfile/SetRepPlaylist.jsx
  src/components/Profile/MainPlayListSection.jsx
  src/components/Profile/PlayListSection.jsx
  src/components/common/PlayList/PlayListItem.jsx
  src/pages/Profile/Profile.jsx
Labels: ✨ Feat, 🎨 Style, [FE] 차다연

#139 유저정보 관련 리팩토링
  src/components/common/Form/SignupForm.jsx
  src/components/common/Toast.jsx
  src/hooks/queries/useUserInfo.jsx
  src/library/apis/api.js
  src/pages/SetProfile/SetProfile.jsx
  src/pages/Signup/SignupDetail.jsx
Labels: ✨ Feat, ♻️ Refactor, [FE] 윤서준

#141 Fix: Styled-components props 에러
  src/components/common/NavBar/NavBar.jsx
Labels: 🐞 Fix, [FE] 이지수

#142 플리 상세 페이지 UI 수정, 댓글/답글 페이지 UI 및 기능 수정
  src/components/PlaylistDetail/CommentForm.jsx
  src/components/PlaylistDetail/CommentItem.jsx
  src/components/PlaylistDetail/CommentList.jsx
  src/components/PlaylistDetail/CommentSection.jsx
  src/components/PlaylistDetail/DetailList.jsx
  src/components/PlaylistDetail/MusicPlayBar.jsx
  src/components/PlaylistDetail/MusicPlayer.jsx
  src/components/PlaylistDetail/MusicWave.jsx
  src/components/PlaylistDetail/PlayListInfo.jsx
  src/components/PlaylistDetail/PlayListModify.jsx
  src/components/common/Image/Image.jsx
  src/img/badge-icon.svg
  src/img/comment-icon.svg
  src/img/left-arrow-icon-white.svg
  src/library/CommentUtils.js
  src/library/DateTimeUtils.js
  src/library/atom.js
  src/pages/PlaylistDetail/Comment.jsx
  src/pages/PlaylistDetail/CommentStyle.jsx
  src/pages/PlaylistDetail/PlaylistDetail.jsx
  src/pages/PlaylistDetail/Reply.jsx
  src/pages/PlaylistSummary/PlaylistSummary.jsx
  src/routes/Router.jsx
Labels: ✨ Feat, 🎨 Style, [FE] 차다연

#144 Style: 플리 수정 모달 UI 수정
  src/components/common/Modal/Modal.jsx
Labels: 🎨 Style, [FE] 이지수

#147 플리 상세/수정 페이지 스타일 버그 및 오류 수정
  src/components/PlaylistDetail/CommentForm.jsx
  src/components/PlaylistDetail/CommentList.jsx
  src/components/PlaylistDetail/PlayListModify.jsx
  src/pages/PlaylistDetail/Comment.jsx
  src/pages/PlaylistDetail/CommentStyle.jsx
  src/pages/PlaylistDetail/PlaylistDetail.jsx
  src/pages/PlaylistDetail/Reply.jsx
  src/pages/PlaylistModify/PlaylistModify.jsx
Labels: 🐞 Fix, 🎨 Style, [FE] 차다연

#143 스플래쉬, 홈 페이지 오류 수정 및 기능 추가
  src/components/Profile/ProfileSection.jsx
  src/img/background-img.svg
  src/pages/Home/Home.jsx
  src/pages/Home/HomeStyle.jsx
  src/pages/Splash/Splash.jsx
Labels: 🐞 Fix, ✨ Feat, 🎨 Style, [FE] 김예지

#145 프로필 페이지 UI 수정
  src/components/PlaylistDetail/PlayListInfo.jsx
  src/components/Profile/MainPlayListSection.jsx
  src/components/Profile/PlayListSection.jsx
  src/components/common/Button/Button.jsx
  src/img/background-img.svg
  src/img/background-img2.svg
  src/pages/EditProfile/EditProfile.jsx
  src/pages/Profile/Profile.jsx
  src/pages/Profile/ProfileStyle.jsx
Labels: 🎨 Style, [FE] 차다연

#150 검색 페이지 스타일 수정
  src/components/Search/EmptySearch.jsx
  src/components/Search/SearchResultAll.jsx
  src/pages/Search/Search.jsx
Labels: 🎨 Style, [FE] 이지수

#155 follow 기능 디버깅
  src/components/Profile/FollowUserList.jsx
  src/components/Profile/PlayListSection.jsx
  src/components/Profile/ProfileSection.jsx
  src/components/common/User.jsx
  src/hooks/queries/useFollow.jsx
  src/hooks/queries/useProfile.jsx
  src/pages/CreatePlaylist/CreatePlaylist3.jsx
  src/pages/Profile/Follow.jsx
  src/pages/Profile/Profile.jsx
  src/routes/Router.jsx
Labels: 🐞 Fix, [FE] 김예지

#152 토스트 디자인 수정 & 파일에 적용
  src/components/PlaylistDetail/CommentForm.jsx
  src/components/PlaylistDetail/CommentItem.jsx
  src/components/PlaylistDetail/PlayListModify.jsx
  src/components/common/Toast.jsx
  src/img/error-icon.svg
  src/img/success-icon.svg
  src/img/warning-icon.svg
  src/pages/PlaylistDetail/Comment.jsx
  src/pages/PlaylistDetail/PlaylistDetail.jsx
  src/pages/PlaylistDetail/Reply.jsx
  src/pages/Signup/SignupDetail.jsx
Labels: 🎨 Style, [FE] 이지수

#158 프로필 설정 변경사항 적용
  src/components/common/Button/Button.jsx
  src/img/basic-profile-img.svg
  src/pages/SetProfile/SetProfile.jsx
Labels: ✨ Feat, 🎨 Style, [FE] 윤서준

#154 유저정보 QA 사항 디버깅
  src/components/common/Form/AuthForm.jsx
  src/components/common/Modal/ResignModal.jsx
  src/img/warning-red-icon.svg
  src/pages/Login/Login.jsx
  src/pages/Signup/SignupDetail.jsx
  src/pages/UserInfo/ChangePassword.jsx
  src/pages/UserInfo/ChangePwForm.jsx
  src/pages/UserInfo/UserLeave.jsx
  src/pages/UserInfo/UserLeaveForm.jsx
Labels: 🐞 Fix, ✨ Feat, [FE] 윤서준

#159 Style: 검색 버튼 스타일 수정
  src/components/Search/SearchInput.jsx
  src/pages/Search/SearchStyle.jsx
Labels: 🐞 Fix, 🎨 Style, [FE] 이지수

#168 QA) Toast 스타일 수정
  src/components/common/Toast.jsx
  src/pages/EditProfile/EditProfile.jsx
  src/pages/Login/Login.jsx
  src/pages/PlaylistDetail/Comment.jsx
  src/pages/PlaylistDetail/CommentStyle.jsx
  src/pages/PlaylistDetail/PlaylistDetail.jsx
  src/pages/PlaylistDetail/Reply.jsx
  src/pages/Profile/Profile.jsx
  src/pages/RandomMusic/RandomMusic.jsx
  src/pages/SetProfile/SetProfile.jsx
  src/pages/Signup/SignupDetail.jsx
Labels: 🎨 Style, [FE] 이지수

#156 이벤트 페이지 QA
  src/pages/EventPage/EventPageStyle.jsx
  src/pages/Login/Login.jsx
  src/pages/Splash/Splash.jsx
Labels: 🎨 Style, [FE] 김예지

#170 플리 상세 페이지 QA
  src/components/PlaylistDetail/CommentSection.jsx
  src/pages/PlaylistDetail/PlaylistDetail.jsx
Labels: 🐞 Fix, 🎨 Style, [FE] 차다연

#171 유효성검사 QA 피드백 반영
  src/components/common/Form/AuthForm.jsx
  src/components/common/Form/SignupForm.jsx
  src/components/common/Input/ProfileInput.jsx
  src/pages/UserInfo/ChangePwForm.jsx
  src/pages/UserInfo/UserLeaveForm.jsx
Labels: 🐞 Fix, 🎨 Style, [FE] 윤서준

#173 회원가입 폼 인증번호 필수 입력 기능 구현
  src/components/common/Form/SignupForm.jsx
Labels: 🐞 Fix, [FE] 이지수
