Repository MusicDigging/Mudig_FE, pull requests merged in 2024-01, with the labels that each got.

#174 Fix: 로그인 이후 페이지 찾을 수 없음 버그 수정
  README.md
  src/library/apis/axiosInstance.js
Labels: 🐞 Fix

#185 유저정보 관련 유저 피드백 반영
  src/components/common/Input/AuthInput.jsx
  src/components/common/Input/ProfileInput.jsx
  src/components/common/Input/SignupInput.jsx
  src/pages/Login/Login.jsx
  src/pages/SetProfile/SetProfile.jsx
Labels: 🐞 Fix, ✨ Feat, [FE] 윤서준

#189 플리 수정 모달 변경 사항
  src/components/common/Modal/Modal.jsx
  src/components/common/Toast.jsx
  src/pages/PlaylistModify/PlaylistModify.jsx
  src/styles/GlobalStyle.jsx
Labels: ✨ Feat, 🎨 Style, [FE] 이지수

#194 플리 생성 페이지 변경사항
  src/components/CreatePlaylist/GenreSelection.jsx
  src/components/CreatePlaylist/YearSelection.jsx
  src/components/NewPlaylist/NewPlaylistChip.jsx
  src/img/character-img.svg
  src/img/character-img2.svg
  src/img/character-img3.svg
  src/img/character-img4.svg
  src/img/character-img5.svg
  src/img/loading-circle.svg
  src/img/loading-mudig.svg
  src/pages/CreatePlaylist/CreatePlaylist1.jsx
  src/pages/CreatePlaylist/CreatePlaylist2.jsx
  src/pages/CreatePlaylist/CreatePlaylist3.jsx
  src/pages/CreatePlaylist/CreatePlaylistStyle.jsx
Labels: ✨ Feat, 🎨 Style, [FE] 차다연

#196 프로필/프로필 수정 페이지 변경 사항
  src/components/EditProfile/SetRepPlaylist.jsx
  src/components/Profile/ProfileImage.jsx
  src/components/Profile/ProfileSection.jsx
  src/components/common/Image/Image.jsx
  src/components/common/Image/ProfileImage.jsx
  src/components/common/Input/ProfileInput.jsx
  src/img/basic-profile-img.svg
  src/img/profile-deco-img.svg
  src/pages/EditProfile/EditProfile.jsx
Labels: ✨ Feat, 🎨 Style, [FE] 차다연

#198 플리 상세 페이지 변경 사항
  src/components/PlaylistDetail/CommentForm.jsx
  src/components/PlaylistDetail/PlayListInfo.jsx
  src/img/playlistinfo-mudig.svg
  src/pages/PlaylistDetail/PlaylistDetail.jsx
Labels: 🎨 Style, [FE] 이지수, [FE] 차다연

#200 플리 상세 영상 재생화면 크기 변경 사항
  src/components/PlaylistDetail/MusicPlayer.jsx
Labels: 🎨 Style, [FE] 차다연

#201 유저 피드백 검색 페이지 반영
  src/components/Search/SearchInput.jsx
  src/components/Search/SearchNav.jsx
  src/components/Search/SearchResultAll.jsx
  src/components/Search/SearchResultByType.jsx
  src/components/Search/SearchResultTitle.jsx
  src/components/common/Modal/AddModal.jsx
  src/hooks/queries/useSearch.jsx
  src/img/add-video-icon.svg
  src/pages/Search/Search.jsx
  src/pages/Search/SearchResult.jsx
  src/pages/Search/SearchStyle.jsx
Labels: ✨ Feat, 🎨 Style, [FE] 이지수

#202 이벤트 페이지 UI 변경
  src/img/checkmark.svg
  src/img/close-icon-white.svg
  src/img/eventPageBg.svg
  src/pages/EventPage/EventPage.jsx
  src/pages/EventPage/EventPageStyle.jsx
Labels: 🎨 Style, [FE] 김예지

#204 플리,노래 탭 버튼 추가
  src/components/Search/SearchInput.jsx
  src/components/Search/SearchResultAll.jsx
  src/components/Search/SearchResultByType.jsx
  src/components/Search/SearchResultTitle.jsx
  src/pages/Search/SearchResult.jsx
Labels: ✨ Feat, 🎨 Style, [FE] 이지수

#205 타입스크립트로 수정
  package-lock.json
  package.json
  src/components/PlaylistDetail/PlayListInfo.tsx
  src/components/PlaylistDetail/PlayListModify.tsx
  src/components/Search/RecentSearch.tsx
  src/components/Search/SearchInput.tsx
  src/components/Search/SearchNav.tsx
  src/components/Search/SearchResultAll.tsx
  src/components/Search/SearchResultByType.tsx
  src/components/Search/SearchResultTitle.tsx
  src/components/common/Modal/Modal.tsx
  src/hooks/queries/useSearch.tsx
  src/library/atom.ts
  src/pages/PlaylistModify/PlaylistModify.tsx
  src/pages/Search/Search.tsx
  src/pages/Search/SearchResult.tsx
  src/types/custom.d.ts
  src/types/playlist.ts
  src/types/searchResult.ts
  src/types/user.ts
Labels: ♻️ Refactor, [FE] 이지수

#206 타입스크립트 업데이트
  src/components/common/Button/Button.tsx
  src/components/common/Form/AuthForm.tsx
  src/components/common/Form/SignupForm.tsx
  src/hooks/queries/useRandomMv.tsx
  src/hooks/queries/useUserInfo.tsx
  src/hooks/ussPasswordToggle.tsx
  src/library/apis/api.ts
  src/pages/Login/Login.tsx
  src/pages/RandomMusic/RandomMusic.tsx
Labels: ♻️ Refactor, [FE] 윤서준

#208 타입스크립트 마이그레이션
  README.md
  src/components/Home/MyPlayListTable.tsx
  src/components/Home/PlayListTable.tsx
  src/components/Profile/FollowUserList.tsx
  src/components/common/Header/MainHeader.tsx
  src/components/common/NavBar/NavBar.tsx
  src/components/common/User.tsx
  src/hooks/queries/useFollow.tsx
  src/hooks/queries/useHome.tsx
Labels: ♻️ Refactor, [FE] 김예지

#209 유저정보& 프로필 설정 타입 업데이트
  src/hooks/queries/useUserInfo.tsx
  src/pages/SetProfile/SetProfile.tsx
Labels: ♻️ Refactor, [FE] 윤서준

#210 Refactor: 타입스크립트로 수정
  src/components/PlaylistDetail/PlayListInfo.tsx
  src/components/PlaylistDetail/PlayListModify.tsx
  src/components/Profile/MainPlayListSection.tsx
  src/components/common/PlayList/PlayList.tsx
  src/components/common/PlayList/PlayListItem.tsx
  src/hooks/queries/usePlaylist.tsx
  src/library/atom.ts
  src/pages/NotFound/NotFound.tsx
  src/pages/PlaylistDetail/PlaylistDetail.tsx
  src/pages/PlaylistSummary/PlaylistSummary.tsx
  src/pages/Profile/Profile.tsx
  src/pages/Search/SearchResult.tsx
  src/pages/Signup/SignupDetail 2.tsx
Labels: ♻️ Refactor, [FE] 이지수

#211 Refactor: 타입스크립트 업데이트
  src/components/common/Form/SignupForm.tsx
  src/components/common/Input/AuthInput.tsx
  src/components/common/Input/ProfileInput.tsx
  src/components/common/Input/SignupInput.tsx
  src/components/common/Modal/AddModal.tsx
  src/library/atom.ts
  src/pages/Login/Login.tsx
  src/pages/RandomMusic/RandomMusic.tsx
  src/pages/SetProfile/SetProfile.tsx
  src/pages/Signup/Signup.tsx
  src/pages/Signup/SignupDetail.tsx
  src/pages/UserInfo/ChangePwForm.tsx
  src/pages/UserInfo/UserLeaveForm.tsx
  src/types/input.ts
  src/types/user.ts
Labels: ♻️ Refactor, [FE] 윤서준

#212 홈, 이벤트, 스플래쉬, 팔로우 페이지 타입스크립트 마이그레이션
  src/components/Home/MyPlayListTable.tsx
  src/components/Home/PlayListTable.tsx
  src/components/Profile/FollowUserList.tsx
  src/components/common/User.tsx
  src/hooks/queries/useFollow.tsx
  src/hooks/queries/useHome.tsx
  src/pages/EventPage/EventPage.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/Intro.tsx
  src/pages/Home/MorePlaylist.tsx
  src/pages/NotFound/NotFound.tsx
  src/pages/Profile/Follow.tsx
  src/pages/Splash/Splash.tsx
Labels: ♻️ Refactor, [FE] 김예지

#215 인터페이스 네이밍 수정
  src/components/PlaylistDetail/DetailList.tsx
  src/components/PlaylistDetail/MusicPlayBar.tsx
  src/components/PlaylistDetail/MusicPlayer.tsx
  src/components/PlaylistDetail/PlayListInfo.tsx
  src/components/PlaylistDetail/PlayListModifyList.tsx
  src/components/Profile/MainPlayList.tsx
  src/components/Profile/MainPlayListSection.tsx
  src/components/Profile/PlayListSection.tsx
  src/components/Search/RecentSearch.tsx
  src/components/Search/SearchInput.tsx
  src/components/Search/SearchNav.tsx
  src/components/Search/SearchResultAll.tsx
  src/components/Search/SearchResultByType.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/PlayList/PlayList.tsx
  src/components/common/PlayList/PlayListItem.tsx
  src/hooks/queries/usePlaylist.tsx
  src/library/atom.ts
  src/pages/PlaylistDetail/PlaylistDetail.tsx
  src/pages/PlaylistModify/PlaylistModify.tsx
  src/pages/PlaylistSummary/PlaylistSummary.tsx
  src/pages/Profile/Profile.tsx
  src/pages/Search/Search.tsx
  src/pages/Search/SearchResult.tsx
  src/types/playlist.ts
  src/types/profile.ts
  src/types/search.ts
  src/types/searchResult.ts
  src/types/user.ts
Labels: ♻️ Refactor, [FE] 이지수

#214 interface 이름 규칙 적용 & 파일 분리
  src/components/RandomMv/VideoInfo.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Form/AuthForm.tsx
  src/components/common/Form/SignupForm.tsx
  src/components/common/Input/ProfileInput.tsx
  src/components/common/Modal/AddModal.tsx
  src/hooks/queries/useRandomMv.tsx
  src/hooks/queries/useUserInfo.tsx
  src/library/atom.ts
  src/pages/Signup/SignupDetail.tsx
  src/types/RandomMv.ts
  src/types/setUser.ts
  src/types/user.ts
Labels: [FE] 윤서준

#217 ts interface 네이밍 수정
  src/components/Home/MyPlayListTable.tsx
  src/components/Home/PlayListTable.tsx
  src/components/Profile/FollowUserList.tsx
  src/components/common/NavBar/NavBar.tsx
  src/hooks/queries/useHome.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/Intro.tsx
  src/pages/Home/MorePlaylist.tsx
  src/pages/Profile/Follow.tsx
Labels: ♻️ Refactor, [FE] 김예지

#218 웹 접근성 개선
  src/components/EditProfile/SetRepPlaylist.tsx
  src/components/PlaylistDetail/DetailList.tsx
  src/components/Profile/MainPlayList.tsx
  src/components/Profile/MainPlayListSection.tsx
  src/components/Profile/PlayListSection.tsx
  src/components/Profile/ProfileSection.tsx
  src/components/common/PlayList/PlayListItem.tsx
  src/pages/EditProfile/EditProfile.tsx
  src/pages/PlaylistDetail/Comment.tsx
  src/pages/PlaylistDetail/Reply.tsx
  src/pages/Profile/Profile.tsx
Labels: ♻️ Refactor, [FE] 차다연

#219 웹 접근성 개선
  src/components/common/Input/AuthInput.tsx
  src/components/common/Input/SignupInput.tsx
  src/components/common/Modal/ResignModal.tsx
  src/pages/Signup/SignupDetail.tsx
  src/pages/UserInfo/UserLeaveForm.tsx
Labels: ♻️ Refactor, [FE] 윤서준
