Repository MusicDigging/Mudig_FE, pull requests merged in 2024-02, with the labels that each got.

#222 비밀번호 찾기 & 재설정 기능 구현
  src/hooks/queries/useUserInfo.tsx
  src/pages/FindPassword/FindPassword.tsx
  src/pages/FindPassword/FindPasswordForm.tsx
  src/pages/Login/Login.tsx
  src/pages/ResetPassword/ResetPassword.tsx
  src/pages/ResetPassword/ResetPasswordForm.tsx
  src/routes/Router.tsx
Labels: ✨ Feat, 🎨 Style, [FE] 윤서준

#220 웹 접근성 개선, 스타일 수정
  src/components/PlaylistDetail/DetailList.tsx
  src/components/PlaylistDetail/PlayListInfo.tsx
  src/components/PlaylistDetail/PlayListModifyList.tsx
  src/components/Search/SearchInput.tsx
  src/components/Search/SearchResultAll.tsx
  src/components/Search/SearchResultByType.tsx
  src/components/Search/SearchResultTitle.tsx
  src/components/common/Button/Button.tsx
  src/components/common/Modal/Modal.tsx
  src/components/common/PlayList/PlayListItem.tsx
  src/pages/PlaylistDetail/PlaylistDetail.tsx
  src/pages/PlaylistModify/PlaylistModify.tsx
  src/pages/PlaylistSummary/PlaylistSummary.tsx
  src/pages/Search/SearchResult.tsx
Labels: ♻️ Refactor, 🎨 Style, [FE] 이지수

#225 소셜 로그인
  src/components/common/Form/AuthForm.tsx
  src/hooks/useSocialLogin.tsx
  src/pages/Login/Login.tsx
  src/pages/Signup/Signup.tsx
Labels: ♻️ Refactor
